#pragma once
namespace Utilities
{
	union MultiMapUnion
	{
		void* ptrToDelete = nullptr;
		MultiMap<unsigned char, unsigned char>* CPPmultimap1;
		MultiMap<unsigned char, char>* CPPmultimap2;
		MultiMap<unsigned char, short>* CPPmultimap3;
		MultiMap<unsigned char, unsigned short>* CPPmultimap4;
		MultiMap<unsigned char, int>* CPPmultimap5;
		MultiMap<unsigned char, unsigned int>* CPPmultimap6;
		MultiMap<unsigned char, long long>* CPPmultimap7;
		MultiMap<unsigned char, unsigned long long>* CPPmultimap8;
		MultiMap<unsigned char, float>* CPPmultimap9;
		MultiMap<unsigned char, double>* CPPmultimap10;
		MultiMap<unsigned char, wchar_t>* CPPmultimap11;
		MultiMap<unsigned char, bool>* CPPmultimap12;
		MultiMap<unsigned char, std::wstring>* CPPmultimap13;
		MultiMap<unsigned char, __int64>* CPPmultimap14;

		MultiMap<char, unsigned char>* CPPmultimap15;
		MultiMap<char, char>* CPPmultimap16;
		MultiMap<char, short>* CPPmultimap17;
		MultiMap<char, unsigned short>* CPPmultimap18;
		MultiMap<char, int>* CPPmultimap19;
		MultiMap<char, unsigned int>* CPPmultimap20;
		MultiMap<char, long long>* CPPmultimap21;
		MultiMap<char, unsigned long long>* CPPmultimap22;
		MultiMap<char, float>* CPPmultimap23;
		MultiMap<char, double>* CPPmultimap24;
		MultiMap<char, wchar_t>* CPPmultimap25;
		MultiMap<char, bool>* CPPmultimap26;
		MultiMap<char, std::wstring>* CPPmultimap27;
		MultiMap<char, __int64>* CPPmultimap28;

		MultiMap<short, unsigned char>* CPPmultimap29;
		MultiMap<short, char>* CPPmultimap30;
		MultiMap<short, short>* CPPmultimap31;
		MultiMap<short, unsigned short>* CPPmultimap32;
		MultiMap<short, int>* CPPmultimap33;
		MultiMap<short, unsigned int>* CPPmultimap34;
		MultiMap<short, long long>* CPPmultimap35;
		MultiMap<short, unsigned long long>* CPPmultimap36;
		MultiMap<short, float>* CPPmultimap37;
		MultiMap<short, double>* CPPmultimap38;
		MultiMap<short, wchar_t>* CPPmultimap39;
		MultiMap<short, bool>* CPPmultimap40;
		MultiMap<short, std::wstring>* CPPmultimap41;
		MultiMap<short, __int64>* CPPmultimap42;

		MultiMap<unsigned short, unsigned char>* CPPmultimap43;
		MultiMap<unsigned short, char>* CPPmultimap44;
		MultiMap<unsigned short, short>* CPPmultimap45;
		MultiMap<unsigned short, unsigned short>* CPPmultimap46;
		MultiMap<unsigned short, int>* CPPmultimap47;
		MultiMap<unsigned short, unsigned int>* CPPmultimap48;
		MultiMap<unsigned short, long long>* CPPmultimap49;
		MultiMap<unsigned short, unsigned long long>* CPPmultimap50;
		MultiMap<unsigned short, float>* CPPmultimap51;
		MultiMap<unsigned short, double>* CPPmultimap52;
		MultiMap<unsigned short, wchar_t>* CPPmultimap53;
		MultiMap<unsigned short, bool>* CPPmultimap54;
		MultiMap<unsigned short, std::wstring>* CPPmultimap55;
		MultiMap<unsigned short, __int64>* CPPmultimap56;

		MultiMap<int, unsigned char>* CPPmultimap57;
		MultiMap<int, char>* CPPmultimap58;
		MultiMap<int, short>* CPPmultimap59;
		MultiMap<int, unsigned short>* CPPmultimap60;
		MultiMap<int, int>* CPPmultimap61;
		MultiMap<int, unsigned int>* CPPmultimap62;
		MultiMap<int, long long>* CPPmultimap63;
		MultiMap<int, unsigned long long>* CPPmultimap64;
		MultiMap<int, float>* CPPmultimap65;
		MultiMap<int, double>* CPPmultimap66;
		MultiMap<int, wchar_t>* CPPmultimap67;
		MultiMap<int, bool>* CPPmultimap68;
		MultiMap<int, std::wstring>* CPPmultimap69;
		MultiMap<int, __int64>* CPPmultimap70;

		MultiMap<unsigned int, unsigned char>* CPPmultimap71;
		MultiMap<unsigned int, char>* CPPmultimap72;
		MultiMap<unsigned int, short>* CPPmultimap73;
		MultiMap<unsigned int, unsigned short>* CPPmultimap74;
		MultiMap<unsigned int, int>* CPPmultimap75;
		MultiMap<unsigned int, unsigned int>* CPPmultimap76;
		MultiMap<unsigned int, long long>* CPPmultimap77;
		MultiMap<unsigned int, unsigned long long>* CPPmultimap78;
		MultiMap<unsigned int, float>* CPPmultimap79;
		MultiMap<unsigned int, double>* CPPmultimap80;
		MultiMap<unsigned int, wchar_t>* CPPmultimap81;
		MultiMap<unsigned int, bool>* CPPmultimap82;
		MultiMap<unsigned int, std::wstring>* CPPmultimap83;
		MultiMap<unsigned int, __int64>* CPPmultimap84;

		MultiMap<long long, unsigned char>* CPPmultimap85;
		MultiMap<long long, char>* CPPmultimap86;
		MultiMap<long long, short>* CPPmultimap87;
		MultiMap<long long, unsigned short>* CPPmultimap88;
		MultiMap<long long, int>* CPPmultimap89;
		MultiMap<long long, unsigned int>* CPPmultimap90;
		MultiMap<long long, long long>* CPPmultimap91;
		MultiMap<long long, unsigned long long>* CPPmultimap92;
		MultiMap<long long, float>* CPPmultimap93;
		MultiMap<long long, double>* CPPmultimap94;
		MultiMap<long long, wchar_t>* CPPmultimap95;
		MultiMap<long long, bool>* CPPmultimap96;
		MultiMap<long long, std::wstring>* CPPmultimap97;
		MultiMap<long long, __int64>* CPPmultimap98;

		MultiMap<unsigned long long, unsigned char>* CPPmultimap99;
		MultiMap<unsigned long long, char>* CPPmultimap100;
		MultiMap<unsigned long long, short>* CPPmultimap101;
		MultiMap<unsigned long long, unsigned short>* CPPmultimap102;
		MultiMap<unsigned long long, int>* CPPmultimap103;
		MultiMap<unsigned long long, unsigned int>* CPPmultimap104;
		MultiMap<unsigned long long, long long>* CPPmultimap105;
		MultiMap<unsigned long long, unsigned long long>* CPPmultimap106;
		MultiMap<unsigned long long, float>* CPPmultimap107;
		MultiMap<unsigned long long, double>* CPPmultimap108;
		MultiMap<unsigned long long, wchar_t>* CPPmultimap109;
		MultiMap<unsigned long long, bool>* CPPmultimap110;
		MultiMap<unsigned long long, std::wstring>* CPPmultimap111;
		MultiMap<unsigned long long, __int64>* CPPmultimap112;

		MultiMap<float, unsigned char>* CPPmultimap113;
		MultiMap<float, char>* CPPmultimap114;
		MultiMap<float, short>* CPPmultimap115;
		MultiMap<float, unsigned short>* CPPmultimap116;
		MultiMap<float, int>* CPPmultimap117;
		MultiMap<float, unsigned int>* CPPmultimap118;
		MultiMap<float, long long>* CPPmultimap119;
		MultiMap<float, unsigned long long>* CPPmultimap120;
		MultiMap<float, float>* CPPmultimap121;
		MultiMap<float, double>* CPPmultimap122;
		MultiMap<float, wchar_t>* CPPmultimap123;
		MultiMap<float, bool>* CPPmultimap124;
		MultiMap<float, std::wstring>* CPPmultimap125;
		MultiMap<float, __int64>* CPPmultimap126;

		MultiMap<double, unsigned char>* CPPmultimap127;
		MultiMap<double, char>* CPPmultimap128;
		MultiMap<double, short>* CPPmultimap129;
		MultiMap<double, unsigned short>* CPPmultimap130;
		MultiMap<double, int>* CPPmultimap131;
		MultiMap<double, unsigned int>* CPPmultimap132;
		MultiMap<double, long long>* CPPmultimap133;
		MultiMap<double, unsigned long long>* CPPmultimap134;
		MultiMap<double, float>* CPPmultimap135;
		MultiMap<double, double>* CPPmultimap136;
		MultiMap<double, wchar_t>* CPPmultimap137;
		MultiMap<double, bool>* CPPmultimap138;
		MultiMap<double, std::wstring>* CPPmultimap139;
		MultiMap<double, __int64>* CPPmultimap140;

		MultiMap<wchar_t, unsigned char>* CPPmultimap141;
		MultiMap<wchar_t, char>* CPPmultimap142;
		MultiMap<wchar_t, short>* CPPmultimap143;
		MultiMap<wchar_t, unsigned short>* CPPmultimap144;
		MultiMap<wchar_t, int>* CPPmultimap145;
		MultiMap<wchar_t, unsigned int>* CPPmultimap146;
		MultiMap<wchar_t, long long>* CPPmultimap147;
		MultiMap<wchar_t, unsigned long long>* CPPmultimap148;
		MultiMap<wchar_t, float>* CPPmultimap149;
		MultiMap<wchar_t, double>* CPPmultimap150;
		MultiMap<wchar_t, wchar_t>* CPPmultimap151;
		MultiMap<wchar_t, bool>* CPPmultimap152;
		MultiMap<wchar_t, std::wstring>* CPPmultimap153;
		MultiMap<wchar_t, __int64>* CPPmultimap154;

		MultiMap<bool, unsigned char>* CPPmultimap155;
		MultiMap<bool, char>* CPPmultimap156;
		MultiMap<bool, short>* CPPmultimap157;
		MultiMap<bool, unsigned short>* CPPmultimap158;
		MultiMap<bool, int>* CPPmultimap159;
		MultiMap<bool, unsigned int>* CPPmultimap160;
		MultiMap<bool, long long>* CPPmultimap161;
		MultiMap<bool, unsigned long long>* CPPmultimap162;
		MultiMap<bool, float>* CPPmultimap163;
		MultiMap<bool, double>* CPPmultimap164;
		MultiMap<bool, wchar_t>* CPPmultimap165;
		MultiMap<bool, bool>* CPPmultimap166;
		MultiMap<bool, std::wstring>* CPPmultimap167;
		MultiMap<bool, __int64>* CPPmultimap168;

		MultiMap<std::wstring, unsigned char>* CPPmultimap169;
		MultiMap<std::wstring, char>* CPPmultimap170;
		MultiMap<std::wstring, short>* CPPmultimap171;
		MultiMap<std::wstring, unsigned short>* CPPmultimap172;
		MultiMap<std::wstring, int>* CPPmultimap173;
		MultiMap<std::wstring, unsigned int>* CPPmultimap174;
		MultiMap<std::wstring, long long>* CPPmultimap175;
		MultiMap<std::wstring, unsigned long long>* CPPmultimap176;
		MultiMap<std::wstring, float>* CPPmultimap177;
		MultiMap<std::wstring, double>* CPPmultimap178;
		MultiMap<std::wstring, wchar_t>* CPPmultimap179;
		MultiMap<std::wstring, bool>* CPPmultimap180;
		MultiMap<std::wstring, std::wstring>* CPPmultimap181;
		MultiMap<std::wstring, __int64>* CPPmultimap182;

		MultiMap<__int64, unsigned char>* CPPmultimap183;
		MultiMap<__int64, char>* CPPmultimap184;
		MultiMap<__int64, short>* CPPmultimap185;
		MultiMap<__int64, unsigned short>* CPPmultimap186;
		MultiMap<__int64, int>* CPPmultimap187;
		MultiMap<__int64, unsigned int>* CPPmultimap188;
		MultiMap<__int64, long long>* CPPmultimap189;
		MultiMap<__int64, unsigned long long>* CPPmultimap190;
		MultiMap<__int64, float>* CPPmultimap191;
		MultiMap<__int64, double>* CPPmultimap192;
		MultiMap<__int64, wchar_t>* CPPmultimap193;
		MultiMap<__int64, bool>* CPPmultimap194;
		MultiMap<__int64, std::wstring>* CPPmultimap195;
		MultiMap<__int64, __int64>* CPPmultimap196;
	};
}